epochs = 2
exemplars = 3000
batch_size = 120

methods = {
    'icarl': {
        'NETWORK': 'resnet32',
        'BATCH_SIZE': batch_size,
        'NUM_EXEMPLARS_PER_CLASS': 0,
        'MAX_NUM_EXEMPLARS': exemplars,
        'EXEMPLAR_SELECTION_METHOD': 'herding',
        'GRIDSEARCH_TASKS': -1,
        'NUM_EPOCHS': epochs,
        'LR': 0.1,
        'LR_MIN': 1e-4,
        'LR_FACTOR': 3,
        'LR_PATIENCE': 5,
        'CLIPPING': 10000,
        'WEIGHT_DECAY': 0.0,
        'WARMUP_NEPOCHS': 0,
        'WARMUP_LR_FACTOR': 1.0,
        'MULTI_SOFTMAX': False,
        'FIX_BN': False,
        'EVAL_ON_TRAIN': False,
        'NUM_WORKERS': 4,
        'PIN_MEMORY': False,
    },
    'r_walk': {
        'NETWORK': 'resnet32',
        'BATCH_SIZE': batch_size,
        'NUM_EXEMPLARS_PER_CLASS': 0,
        'MAX_NUM_EXEMPLARS': exemplars,
        'EXEMPLAR_SELECTION_METHOD': 'distance',
        'GRIDSEARCH_TASKS': -1,
        'NUM_EPOCHS': epochs,
        'LR': 0.1,
        'LR_MIN': 1e-4,
        'LR_FACTOR': 3,
        'LR_PATIENCE': 5,
        'CLIPPING': 10000,
        'WEIGHT_DECAY': 0.0,
        'WARMUP_NEPOCHS': 0,
        'WARMUP_LR_FACTOR': 1.0,
        'MULTI_SOFTMAX': False,
        'FIX_BN': False,
        'EVAL_ON_TRAIN': True,
        'NUM_WORKERS': 4,
        'PIN_MEMORY': False,
    },
    'path_integral': {
        'NETWORK': 'resnet32',
        'BATCH_SIZE': batch_size,
        'NUM_EXEMPLARS_PER_CLASS': 0,
        'MAX_NUM_EXEMPLARS': exemplars,
        'EXEMPLAR_SELECTION_METHOD': 'herding',
        'GRIDSEARCH_TASKS': -1,
        'NUM_EPOCHS': epochs,
        'LR': 0.1,
        'LR_MIN': 1e-4,
        'LR_FACTOR': 3,
        'LR_PATIENCE': 5,
        'CLIPPING': 10000,
        'WEIGHT_DECAY': 0.0,
        'WARMUP_NEPOCHS': 0,
        'WARMUP_LR_FACTOR': 1.0,
        'MULTI_SOFTMAX': False,
        'FIX_BN': False,
        'EVAL_ON_TRAIN': True,
        'NUM_WORKERS': 4,
        'PIN_MEMORY': False,
    },
    'ewc': {
        'NETWORK': 'resnet32',
        'BATCH_SIZE': batch_size,
        'NUM_EXEMPLARS_PER_CLASS': 0,
        'MAX_NUM_EXEMPLARS': exemplars,
        'EXEMPLAR_SELECTION_METHOD': 'herding',
        'GRIDSEARCH_TASKS': -1,
        'NUM_EPOCHS': epochs,
        'LR': 0.1,
        'LR_MIN': 1e-4,
        'LR_FACTOR': 3,
        'LR_PATIENCE': 5,
        'CLIPPING': 10000,
        'WEIGHT_DECAY': 0.0,
        'WARMUP_NEPOCHS': 0,
        'WARMUP_LR_FACTOR': 1.0,
        'MULTI_SOFTMAX': False,
        'FIX_BN': False,
        'EVAL_ON_TRAIN': False,
        'NUM_WORKERS': 4,
        'PIN_MEMORY': False,
    },
    'il2m': {
        'NETWORK': 'resnet32',
        'BATCH_SIZE': batch_size,
        'NUM_EXEMPLARS_PER_CLASS': 0,
        'MAX_NUM_EXEMPLARS': exemplars,
        'EXEMPLAR_SELECTION_METHOD': 'herding',
        'GRIDSEARCH_TASKS': -1,
        'NUM_EPOCHS': epochs,
        'LR': 0.1,
        'LR_MIN': 1e-4,
        'LR_FACTOR': 3,
        'LR_PATIENCE': 5,
        'CLIPPING': 10000,
        'WEIGHT_DECAY': 0.0,
        'WARMUP_NEPOCHS': 0,
        'WARMUP_LR_FACTOR': 1.0,
        'MULTI_SOFTMAX': False,
        'FIX_BN': False,
        'EVAL_ON_TRAIN': False,
        'NUM_WORKERS': 4,
        'PIN_MEMORY': False,
    },
    'bic': {
        'NETWORK': 'resnet32',
        'BATCH_SIZE': 50,
        'NUM_EXEMPLARS_PER_CLASS': 0,
        'MAX_NUM_EXEMPLARS': 3000,
        'EXEMPLAR_SELECTION_METHOD': 'herding',
        'GRIDSEARCH_TASKS': -1,
        'NUM_EPOCHS': 10,
        'LR': 0.1,
        'LR_MIN': 1e-4,
        'LR_FACTOR': 3,
        'LR_PATIENCE': 5,
        'CLIPPING': 10000,
        'MOMENTUM': 0.0,
        'WEIGHT_DECAY': 0.0,
        'WARMUP_NEPOCHS': 0,
        'WARMUP_LR_FACTOR': 1.0,
        'MULTI_SOFTMAX': False,
        'FIX_BN': False,
        'EVAL_ON_TRAIN': True,
        'NUM_WORKERS': 4,
        'PIN_MEMORY': False,
    },
    'mas': {
        'NETWORK': 'resnet32',
        'BATCH_SIZE': batch_size,
        'NUM_EXEMPLARS_PER_CLASS': 0,
        'MAX_NUM_EXEMPLARS': exemplars,
        'EXEMPLAR_SELECTION_METHOD': 'herding',
        'GRIDSEARCH_TASKS': -1,
        'NUM_EPOCHS': epochs,
        'LR': 0.1,
        'LR_MIN': 1e-4,
        'LR_FACTOR': 3,
        'LR_PATIENCE': 5,
        'CLIPPING': 10000,
        'WEIGHT_DECAY': 0.0,
        'WARMUP_NEPOCHS': 0,
        'WARMUP_LR_FACTOR': 1.0,
        'MULTI_SOFTMAX': False,
        'FIX_BN': False,
        'EVAL_ON_TRAIN': False,
        'NUM_WORKERS': 4,
        'PIN_MEMORY': False,
    },
    'lwf': {
        'NETWORK': 'resnet32',
        'BATCH_SIZE': batch_size,
        'NUM_EXEMPLARS_PER_CLASS': 0,
        'MAX_NUM_EXEMPLARS': exemplars,
        'EXEMPLAR_SELECTION_METHOD': 'herding',
        'GRIDSEARCH_TASKS': -1,
        'NUM_EPOCHS': epochs,
        'LR': 0.1,
        'LR_MIN': 1e-4,
        'LR_FACTOR': 3,
        'LR_PATIENCE': 5,
        'CLIPPING': 10000,
        'WEIGHT_DECAY': 0.0,
        'WARMUP_NEPOCHS': 0,
        'WARMUP_LR_FACTOR': 1.0,
        'MULTI_SOFTMAX': False,
        'FIX_BN': False,
        'EVAL_ON_TRAIN': False,
        'NUM_WORKERS': 4,
        'PIN_MEMORY': False,
    },
    'lwm': {
        'NETWORK': 'resnet32',
        'BATCH_SIZE': batch_size,
        'NUM_EXEMPLARS_PER_CLASS': 0,
        'MAX_NUM_EXEMPLARS': exemplars,
        'EXEMPLAR_SELECTION_METHOD': 'herding',
        'GRIDSEARCH_TASKS': -1,
        'NUM_EPOCHS': epochs,
        'LR': 0.1,
        'LR_MIN': 1e-4,
        'LR_FACTOR': 3,
        'LR_PATIENCE': 5,
        'CLIPPING': 10000,
        'WEIGHT_DECAY': 0.0,
        'WARMUP_NEPOCHS': 0,
        'WARMUP_LR_FACTOR': 1.0,
        'MULTI_SOFTMAX': False,
        'FIX_BN': False,
        'EVAL_ON_TRAIN': False,
        'NUM_WORKERS': 4,
        'PIN_MEMORY': False,
    },

    'eeil': {
            'NETWORK': 'resnet32',
            'BATCH_SIZE': batch_size,
            'NUM_EXEMPLARS_PER_CLASS': 0,
            'MAX_NUM_EXEMPLARS': exemplars,
            'EXEMPLAR_SELECTION_METHOD': 'herding',
            'GRIDSEARCH_TASKS': -1,
            'NUM_EPOCHS': epochs,
            'LR': 0.1,
            'LR_MIN': 1e-4,
            'LR_FACTOR': 3,
            'LR_PATIENCE': 5,
            'CLIPPING': 10000,
            'WEIGHT_DECAY': 0.0,
            'WARMUP_NEPOCHS': 0,
            'WARMUP_LR_FACTOR': 1.0,
            'MULTI_SOFTMAX': False,
            'FIX_BN': False,
            'EVAL_ON_TRAIN': False,
            'NUM_WORKERS': 4,
            'PIN_MEMORY': False,
        },
}

DATABASE = "malware"
RESULT_PATH = './results/'
SAVE_MODELS = False
LOG = ['disk']
GPU = 0
LAST_LAYER_ANALYSIS = True
MAX_ADV_PER_EPSILON = 2000
EPSILONS = [
    0.03,
    0.1,
    0.3,
    0.5,
]
